# PostgreSQL — local
spring.datasource.url=jdbc:postgresql://localhost:5432/blockchain
spring.datasource.username=postgres
spring.datasource.password=postgres

# HikariCP connection pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.pool-name=BlockchainHikariPool

# Show SQL in dev
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Encryption — OFF in dev
app.encryption.enabled=false

# BCrypt strength — lower in dev for faster hashing
app.security.bcrypt-strength=8

# CORS — local Angular dev server
app.cors.allowed-origins=http://localhost:4200
#app.cors.allowed-origins=http://192.168.22.59:4200

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=300s

# Async thread pool
app.async.core-pool-size=10
app.async.max-pool-size=50
app.async.queue-capacity=500
