# PostgreSQL — local
spring.datasource.url=jdbc:postgresql://localhost:5432/blockchain
spring.datasource.username=postgres
spring.datasource.password=postgres

# Show SQL in dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Encryption — OFF in dev
app.encryption.enabled=false

# BCrypt strength — lower in dev for faster hashing (prod default=10)
app.security.bcrypt-strength=8

# CORS — local Angular dev server
app.cors.allowed-origins=http://localhost:4200
