# PostgreSQL — prod
spring.datasource.url=jdbc:postgresql://localhost:5432/blockchain
spring.datasource.username=postgres
spring.datasource.password=postgres

# HikariCP — tuned for high concurrency
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.pool-name=BlockchainHikariPool

# No SQL logging in prod
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Encryption — ON in prod
app.encryption.enabled=true

# CORS — prod frontend URL
app.cors.allowed-origins=http://localhost:4200
#app.cors.allowed-origins=http://192.168.22.59:4200

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=50000,expireAfterWrite=300s

# Async thread pool
app.async.core-pool-size=20
app.async.max-pool-size=200
app.async.queue-capacity=2000
