
# PostgreSQL — prod
spring.datasource.url=jdbc:postgresql://localhost:5432/blockchain
spring.datasource.username=postgres
spring.datasource.password=postgres

# No SQL logging in prod
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Encryption — ON in prod
app.encryption.enabled=true

# CORS — prod frontend URL
app.cors.allowed-origins=http://localhost:4200
